version: '3.8'

services:
  uvbot:
    build: .
    volumes:
      - uv_data:/app/data
    environment:
      - TOKEN=${DISCORD_TOKEN}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    restart: unless-stopped

volumes:
  uv_data: